replicaCount: 2

image:
  repository: ghcr.io/bmiazek18/facebook-clone1
  tag: "542324dbb618286964bb63e9a497cfefa305f8ee"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "traefik" 
  host: app.lab-bm.com
  path: /
  pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 384Mi