spring.application.name=groups-service
spring.main.web-application-type=none

# Configure gRPC server to run on port 9098
grpc.server.port=9098

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/users_db}
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Configure gRPC client to communicate with feed-service
grpc.client.feed-service.address=${FEED_SERVICE_GRPC_ADDRESS:dns:///localhost:9092}
grpc.client.feed-service.negotiation-type=plaintext

# Configure gRPC client to communicate with user-service
grpc.client.user-service.address=${USER_SERVICE_GRPC_ADDRESS:dns:///userservice:9090}
grpc.client.user-service.negotiation-type=plaintext

# Redis Configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# Quartz Configuration
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=always
spring.quartz.properties.org.quartz.jobStore.isClustered=true
spring.quartz.properties.org.quartz.jobStore.clusterCheckinInterval=20000



