FROM quay.io/keycloak/keycloak:26.6.2 AS builder

# Kopiowanie zbudowanych w workflow plików JAR (React Theme + Java SPI)
COPY dist_jars/*.jar /opt/keycloak/providers/

# Optymalizacja pod PostgreSQL oraz włączenie endpointów diagnostycznych dla K8s
ENV KC_DB=postgres
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:26.6.2
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]