<template>
    <div class="px-4 py-4">
        <p class="text-gray-500 text-xs mb-4 leading-relaxed">
            Użyj wygenerowanego tekstu alternatywnego do tego zdjęcia lub dodaj niestandardowy:
        </p>

        <div class="flex items-start justify-between cursor-pointer mb-3 group p-2 rounded-lg hover:bg-gray-100 transition" @click="selectedOption = 'auto'">
            <span class="text-gray-800 text-xs pr-2 leading-tight">{{ autoGeneratedText }}</span>
            <div class="w-4 h-4 rounded-full border-2 flex items-center justify-center shrink-0 transition mt-0.5" :class="selectedOption === 'auto' ? 'border-blue-600' : 'border-gray-300 group-hover:border-gray-400'">
                <div v-if="selectedOption === 'auto'" class="w-2 h-2 bg-blue-600 rounded-full"></div>
            </div>
        </div>

        <div class="flex items-start gap-2 mt-2">
            <textarea v-model="customText" @focus="selectedOption = 'custom'" placeholder="Niestandardowy tekst..." class="flex-1 border rounded-lg p-2 text-xs focus:outline-none focus:ring-1 focus:ring-blue-500 transition resize-none h-20 bg-white" :class="selectedOption === 'custom' ? 'border-blue-500' : 'border-gray-300'"></textarea>
            <div class="w-4 h-4 rounded-full border-2 flex items-center justify-center shrink-0 mt-2 cursor-pointer transition" :class="selectedOption === 'custom' ? 'border-blue-600' : 'border-gray-300 hover:border-gray-400'" @click="selectedOption = 'custom'">
                <div v-if="selectedOption === 'custom'" class="w-2 h-2 bg-blue-600 rounded-full"></div>
            </div>
        </div>

        <button @click="saveAltText" class="w-full mt-4 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold py-2 rounded-lg transition shadow-sm">
            Zapisz zmiany
        </button>
    </div>
</template>

<script setup lang="ts">
import { ref, watch, inject, computed, type Ref } from 'vue';
import type { StoryElement } from '@/types/StoryElement';

const emit = defineEmits<{
    (e: 'save-alt-text', text: string): void;
}>();

const selectedElement = inject<Ref<StoryElement | undefined>>('selectedElement');

const currentAltText = computed(() => {
    if (selectedElement?.value?.type === 'image') {
        return selectedElement.value.altText;
    }
    return '';
});

const selectedOption = ref<'auto' | 'custom'>('auto');
const customText = ref('');
const autoGeneratedText = "Może być zdjęciem przedstawiającym zbiornik wody";

watch(currentAltText, (newVal) => {
    if (newVal && newVal !== autoGeneratedText) {
        selectedOption.value = 'custom';
        customText.value = newVal;
    } else {
        selectedOption.value = 'auto';
        customText.value = '';
    }
}, { immediate: true });

const saveAltText = () => {
    const finalText = selectedOption.value === 'auto' ? autoGeneratedText : customText.value;
    emit('save-alt-text', finalText);
};
</script>
