server.port=8099
spring.application.name=marketplace-edge-service

# Configure gRPC client to communicate with marketplace-service
grpc.client.marketplace-service.address=${MARKETPLACE_SERVICE_GRPC_ADDRESS:dns:///localhost:9096}
grpc.client.marketplace-service.negotiation-type=plaintext

# Graceful Shutdown
spring.lifecycle.timeout-per-shutdown-phase=30s
server.shutdown=graceful

# Actuator Endpoint Exposure
management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.health.show-details=always
