<template>
    <div class="px-4 py-4">
        <p class="text-gray-500 text-xs mb-4 leading-relaxed">
            Użyj wygenerowanego tekstu alternatywnego do tego zdjęcia lub dodaj niestandardowy:
        </p>

        <div class="flex items-start justify-between cursor-pointer mb-3 group p-2 rounded-lg hover:bg-gray-100 transition" @click="selectedOption = 'auto'">
            <span class="text-gray-800 text-xs pr-2 leading-tight">{{ autoGeneratedText }}</span>
            <div class="w-4 h-4 rounded-full border-2 flex items-center justify-center shrink-0 transition mt-0.5" :class="selectedOption === 'auto' ? 'border-blue-600' : 'border-gray-300 group-hover:border-gray-400'">
                <div v-if="selectedOption === 'auto'" class="w-2 h-2 bg-blue-600 rounded-full"></div>
            </div>
        </div>

        <div class="flex items-start gap-2 mt-2">
            <textarea v-model="customText" @focus="selectedOption = 'custom'" placeholder="Niestandardowy tekst..." class="flex-1 border rounded-lg p-2 text-xs focus:outline-none focus:ring-1 focus:ring-blue-500 transition resize-none h-20 bg-white" :class="selectedOption === 'custom' ? 'border-blue-500' : 'border-gray-300'"></textarea>
            <div class="w-4 h-4 rounded-full border-2 flex items-center justify-center shrink-0 mt-2 cursor-pointer transition" :class="selectedOption === 'custom' ? 'border-blue-600' : 'border-gray-300 hover:border-gray-400'" @click="selectedOption = 'custom'">
                <div v-if="selectedOption === 'custom'" class="w-2 h-2 bg-blue-600 rounded-full"></div>
            </div>
        </div>


    </div>
</template>

<script setup lang="ts">
import { ref, watch} from 'vue';


interface Props {
  altText: string;
}

const props = defineProps<Props>();
const emit = defineEmits(['update:altText']);

const selectedOption = ref<'auto' | 'custom'>(props.altText ? 'custom' : 'auto');
const customText = ref(props.altText || '');
const autoGeneratedText = "Może być zdjęciem przedstawiającym zbiornik wody";


watch([selectedOption, customText], () => {
  if (selectedOption.value === 'custom') {
    emit('update:altText', customText.value);
  } else {
    emit('update:altText', autoGeneratedText);
  }
});




</script>
