<script setup lang="ts">
import { ref, watch, onMounted } from 'vue';

// IKONY
import Cog from 'vue-material-design-icons/Cog.vue';
import FormatFont from 'vue-material-design-icons/FormatFont.vue';
import ImageIcon from 'vue-material-design-icons/Image.vue';
import MusicNote from 'vue-material-design-icons/MusicNote.vue';
import StickerEmoji from 'vue-material-design-icons/StickerEmoji.vue';
import AlphaABox from 'vue-material-design-icons/AlphaABox.vue';
import ChevronUp from 'vue-material-design-icons/ChevronUp.vue';
import ChevronDown from 'vue-material-design-icons/ChevronDown.vue';

const props = defineProps<{
  isMusicModalOpen: boolean;
  // [NEW] Otrzymujemy aktualny tekst zaznaczonego elementu
  currentAltText?: string;
  // [NEW] Czy zaznaczony element to obrazek (żeby wiedzieć czy pokazywać opcję)
  isImageSelected: boolean;
}>();

const emit = defineEmits<{
  (e: 'add-text'): void;
  (e: 'add-image'): void;
  (e: 'toggle-music'): void;
  // [NEW] Emitujemy zapisanie tekstu
  (e: 'save-alt-text', text: string): void;
}>();

// --- LOGIKA TEKSTU ALTERNATYWNEGO ---
const isAltTextExpanded = ref(false);
const selectedOption = ref<'auto' | 'custom'>('auto');
const customText = ref('');
const autoGeneratedText = "Może być zdjęciem przedstawiającym zbiornik wody";

// Przełączanie widoczności sekcji
const toggleAltTextSection = () => {
    if (!props.isImageSelected) {
        alert("Wybierz zdjęcie, aby edytować tekst alternatywny.");
        return;
    }
    isAltTextExpanded.value = !isAltTextExpanded.value;
};

// Aktualizacja pól gdy zmienia się zaznaczony element
watch(() => props.currentAltText, (newVal) => {
    if (newVal && newVal !== autoGeneratedText) {
        selectedOption.value = 'custom';
        customText.value = newVal;
    } else {
        selectedOption.value = 'auto';
        customText.value = '';
    }
}, { immediate: true });

// Zapisywanie zmian (automatyczne lub na przycisk - tutaj na przycisk dla jasności)
const saveAltText = () => {
    const finalText = selectedOption.value === 'auto' ? autoGeneratedText : customText.value;
    emit('save-alt-text', finalText);
    // Opcjonalnie: zwiń po zapisaniu
    // isAltTextExpanded.value = false;
};
</script>

<template>
  <aside class="w-[360px] flex-shrink-0 bg-white shadow-xl z-20 flex flex-col justify-between h-full border-r border-gray-300 overflow-y-auto custom-scrollbar">
      <div>
        <div class="flex items-center justify-between p-4 border-b border-gray-200 bg-white sticky top-0 z-10">
          <h1 class="text-2xl font-bold text-black">Twoja relacja</h1>
          <div class="bg-gray-100 p-2 rounded-full cursor-pointer hover:bg-gray-200 transition">
            <Cog :size="24" class="text-black"/>
          </div>
        </div>

        <div class="flex items-center gap-3 p-4">
           <div class="w-12 h-12 bg-blue-600 rounded-full flex items-center justify-center text-white font-bold text-xl overflow-hidden">
               <img src="https://i.pravatar.cc/150?img=12" class="w-full h-full object-cover" />
           </div>
           <span class="font-semibold text-lg text-gray-900">Bartosz Mązek</span>
        </div>

        <div class="flex flex-col mt-2 pb-4">

           <div @click="emit('add-text')" class="flex items-center gap-4 px-4 py-3 hover:bg-gray-100 cursor-pointer transition active:scale-95">
              <div class="bg-gray-200 p-2.5 rounded-full border border-gray-300"><FormatFont :size="24" class="text-gray-700"/></div>
              <span class="font-medium text-gray-700 text-sm">Dodaj tekst</span>
           </div>

           <div @click="emit('add-image')" class="flex items-center gap-4 px-4 py-3 hover:bg-gray-100 cursor-pointer transition active:scale-95">
              <div class="bg-gray-200 p-2.5 rounded-full border border-gray-300"><ImageIcon :size="24" class="text-green-600"/></div>
              <span class="font-medium text-gray-700 text-sm">Dodaj zdjęcie</span>
           </div>

           <div @click="emit('toggle-music')" class="flex items-center gap-4 px-4 py-3 hover:bg-gray-100 cursor-pointer transition" :class="{'bg-blue-50 border-l-4 border-blue-500': isMusicModalOpen}">
              <div class="bg-gray-200 p-2.5 rounded-full border border-gray-300"><MusicNote :size="24" class="text-gray-700"/></div>
              <span class="font-medium text-gray-700 text-sm">Dodaj muzykę</span>
           </div>


               <div
                  @click="toggleAltTextSection"
                  class="flex items-center justify-between px-4 py-3 hover:bg-gray-100 cursor-pointer transition"
                  :class="{'bg-gray-50': isAltTextExpanded}"
               >
                  <div class="flex items-center gap-4">
                      <div class="bg-gray-200 p-2.5 rounded-full border border-gray-300"><AlphaABox :size="24" class="text-gray-700"/></div>
                      <span class="font-medium text-gray-700 text-sm">Tekst alternatywny</span>
                  </div>

               </div>

               <div v-if="isAltTextExpanded" class="px-4 py-4 ">
                    <p class="text-gray-500 text-xs mb-4 leading-relaxed">
                        Użyj wygenerowanego tekstu alternatywnego do tego zdjęcia lub dodaj niestandardowy:
                    </p>

                    <div
                        class="flex items-start justify-between cursor-pointer mb-3 group p-2 rounded-lg hover:bg-gray-100 transition"
                        @click="selectedOption = 'auto'"
                    >
                        <span class="text-gray-800 text-xs pr-2 leading-tight">{{ autoGeneratedText }}</span>
                        <div class="w-4 h-4 rounded-full border-2 flex items-center justify-center flex-shrink-0 transition mt-0.5"
                            :class="selectedOption === 'auto' ? 'border-blue-600' : 'border-gray-300 group-hover:border-gray-400'">
                            <div v-if="selectedOption === 'auto'" class="w-2 h-2 bg-blue-600 rounded-full"></div>
                        </div>
                    </div>

                    <div class="flex items-start gap-2 mt-2">
                        <textarea
                            v-model="customText"
                            @focus="selectedOption = 'custom'"
                            placeholder="Niestandardowy tekst..."
                            class="flex-1 border rounded-lg p-2 text-xs focus:outline-none focus:ring-1 focus:ring-blue-500 transition resize-none h-20 bg-white"
                            :class="selectedOption === 'custom' ? 'border-blue-500' : 'border-gray-300'"
                        ></textarea>
                        <div
                            class="w-4 h-4 rounded-full border-2 flex items-center justify-center flex-shrink-0 mt-2 cursor-pointer transition"
                            :class="selectedOption === 'custom' ? 'border-blue-600' : 'border-gray-300 hover:border-gray-400'"
                            @click="selectedOption = 'custom'"
                        >
                            <div v-if="selectedOption === 'custom'" class="w-2 h-2 bg-blue-600 rounded-full"></div>
                        </div>
                    </div>

                    <button @click="saveAltText" class="w-full mt-4 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold py-2 rounded-lg transition shadow-sm">
                        Zapisz zmiany
                    </button>
               </div>
           </div>

        </div>


      <div class="p-4 flex gap-3 shadow-[0_-4px_10px_rgba(0,0,0,0.05)] bg-white z-30 sticky bottom-0">
         <button class="flex-1 py-2.5 rounded-lg bg-gray-200 text-gray-800 font-semibold hover:bg-gray-300 transition text-sm">Odrzuć</button>
         <button class="flex-1 py-2.5 rounded-lg bg-blue-600 text-white font-semibold hover:bg-blue-700 transition shadow-md text-sm">Udostępnij</button>
      </div>
    </aside>
</template>

<style scoped>
.custom-scrollbar::-webkit-scrollbar { width: 5px; }
.custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
.custom-scrollbar::-webkit-scrollbar-thumb { background-color: #d1d5db; border-radius: 20px; }


</style>
