spring.application.name=SearchService

# Database Configuration
spring.datasource.url=jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5434}/users_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=8088
grpc.server.port=9097

# Meilisearch Configuration
meilisearch.host=${MEILI_HOST:http://localhost:7700}
meilisearch.api-key=${MEILI_API_KEY:masterKey}
