spring.application.name=SearchService

# Server Configuration
server.port=8088
grpc.server.port=9097

# Meilisearch Configuration
meilisearch.host=${MEILI_HOST:http://localhost:7700}
meilisearch.api-key=${MEILI_API_KEY:masterKey}

# RabbitMQ Configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# gRPC Client to communicate with user-service
grpc.client.user-service.address=${USER_SERVICE_GRPC_ADDRESS:dns:///localhost:9090}
grpc.client.user-service.negotiation-type=plaintext
