replicaCount: 1

images:
  userService:
    repository: ghcr.io/bmiazek18/facebook-clone1-user-service
    tag: "latest"
  userEdgeService:
    repository: ghcr.io/bmiazek18/facebook-clone1-user-edge-service
    tag: "latest"
  socialgraphService:
    repository: ghcr.io/bmiazek18/facebook-clone1-socialgraph-service
    tag: "latest"
  socialgraphEdgeService:
    repository: ghcr.io/bmiazek18/facebook-clone1-socialgraph-edge-service
    tag: "latest"
  videoAbrService:
    repository: ghcr.io/bmiazek18/facebook-clone1-video-abr-service
    tag: "latest"
  apolloRouter:
    repository: ghcr.io/apollographql/router
    tag: "v2.17.0"

imagePullPolicy: IfNotPresent

apiHost: "api.lab-bm.com"
keycloakJwksUrl: "http://keycloak-service:8080/realms/myrealm/protocol/openid-connect/certs"

config:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql.apps.svc.cluster.local:5432/users_db
  NOTIFICATION_DATASOURCE_URL: jdbc:postgresql://postgresql-notifications.apps.svc.cluster.local:5432/notifications_db
  SPRING_DATA_REDIS_HOST: redis-master.apps.svc.cluster.local
  SPRING_DATA_REDIS_PORT: "6379"
  NEO4J_URI: bolt://neo4j.apps.svc.cluster.local:7687
  NEO4J_USER: neo4j
  MINIO_URL: http://minio.apps.svc.cluster.local:9000
  MINIO_PUBLIC_ENDPOINT: https://media.lab-bm.com
  MEDIA_STABLE_URL_BASE: https://api.lab-bm.com
  USER_SERVICE_GRPC_ADDRESS: dns:///userservice:9090
  SOCIAL_GRAPH_SERVICE_GRPC_ADDRESS: dns:///socialgraph-service:9091
  VAULT_URI: http://vault.apps.svc.cluster.local:8200
  VAULT_TOKEN: vault-root-token
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.observability:4317
  SENTRY_ENVIRONMENT: production

secrets:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: change-me
  NEO4J_PASSWORD: change-me
  MINIO_ACCESS_KEY: change-me
  MINIO_SECRET_KEY: change-me
  SENTRY_DSN: ""
  SENTRY_TRACES_SAMPLE_RATE: "0.1"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
