server.port=8090
spring.application.name=marketplace-service
grpc.server.port=9096

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/users_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${USERS_DB_USER:postgres}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${USERS_DB_PASSWORD:postgres}}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Upload Directory Configuration
app.upload.dir=${UPLOAD_DIR:uploads}

# Kafka Configuration
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9094}

# Redis Configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
